runtime: python38

handlers:
- url: /favicon\.ico
  static_files: resources/static/favicon.ico
  upload: resources/static/favicon\.ico

- url: /robots.txt
  static_files: resources/static/robots.txt
  upload: resources/static/robots.txt

- url: /favicon.ico
  static_files: resources/static/favicon.ico
  upload: resources/static/favicon.ico

- url: /resources/static/images
  static_dir: resources/static/images
  expiration: "30d"

- url: /resources/static
  static_dir: resources/static

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
